templateHairMat = {
'textureDirName': "",
'densityTexture': "",
'rootColorTexture': "",
'tipColorTexture': "",
'widthTexture': "",
'rootWidthTexture': "",
'tipWidthTexture': "",
'stiffnessTexture': "",
'rootStiffnessTexture': "",
'clumpScaleTexture': "",
'clumpRoundnessTexture': "",
'clumpNoiseTexture': "",
'waveScaletexture': "",
'waveFreqTexture': "",
'strandTexture': "",
'lengthTexture': "",
'specularTexture': "",
'matName': "",
'densityTextureChan': '0',
'widthTextureChan': '0',
'rootWidthTextureChan': '0',
'tipWidthTextureChan': '0',
'clumpScaleTextureChan': '0',
'clumpNoiseTextureChan': '0',
'clumpRoundnessTextureChan': '0',
'waveScaleTextureChan': '0',
'waveFreqTextureChan': '0',
'lengthTextureChan': '0',
'stiffnessTextureChan': '0',
'rootStiffnessTextureChan': '0',
'splineMultiplier': 3,
'assetType': 0,
'assetPriority': 0,
'assetGroup': 0,
'width': 1,
'widthNoise': 0,
'clumpNoise': 0,
'clumpNumSubclumps': 0,
'clumpRoundness': 1,
'clumpScale': 0,
'clumpPerVertex': False,
'density': 1,
'lengthNoise': 1,
'lengthScale': 1,
'widthRootScale': 1,
'widthTipScale': 0.1,
'waveRootStraighten': 0,
'waveScale': 0,
'waveScaleNoise': 0.5,
'waveFreq': 3,
'waveFreqNoise': 0.5,
'waveScaleStrand': 1,
'waveScaleClump': 0,
'enableDistanceLOD': True,
'distanceLODStart': 5,
'distanceLODEnd': 10,
'distanceLODFadeStart': 1000,
'distanceLODDensity': 0,
'distanceLODWidth': 1,
'enableDetailLOD': True,
'detailLODStart': 2,
'detailLODEnd': 1,
'detailLODDensity': 1,
'detailLODWidth': 1,
'colorizeLODOption': '0',
'useViewfrustrumCulling': True,
'useBackfaceCulling': False,
'backfaceCullingThreshold': -0.2,
'usePixelDensity': False,
'alpha': 0,
'strandBlendScale': 1,
'baseColor': (0, 0, 0, 0),
'diffuseBlend': 0.5,
'diffuseScale': 0,
'diffuseHairNormalWeight': 0,
'diffuseBoneIndex': '0',
'diffuseBoneLocalPos': (0, 0, 0),
'diffuseNoiseFreqU': 0,
'diffuseNoiseFreqV': 0,
'diffuseNoiseScale': 0,
'diffuseNoiseGain': 0,
'textureBrightness': 0,
'diffuseColor': (0, 0, 0, 0),
'rootColor': (1, 1, 1, 1),
'tipColor': (1, 1, 1, 1),
'glintStrength': 0,
'glintCount': 256,
'glintExponent': 2,
'rootAlphaFalloff': 0,
'rootTipColorWeight': 0.5,
'rootTipColorFalloff': 1,
'shadowSigma': 0.2,
'specularColor': (1, 1, 1, 1),
'specularPrimary': 0.1,
'specularNoiseScale': 0,
'specularEnvScale': 0.25,
'specularPrimaryBreakup': 0,
'specularSecondary': 0.05,
'specularSecondaryOffset': 0.1,
'specularPowerPrimary': 100,
'specularPowerSecondary': 20,
'strandBlendMode': '0',
'useTextures': False,
'useShadows': False,
'shadowDensityScale': 0.5,
'castShadows': True,
'receiveShadows': True,
'backStopRadius': 0,
'bendStiffness': 0,
'interactionStiffness': 0,
'pinStiffness': 1,
'collisionOffset': 0,
'useCollision': False,
'useDynamicPin': False,
'damping': 0,
'friction': 0,
'massScale': 10,
'gravity': (0, 0, -1),
'inertiaScale': 1,
'inertiaLimit': 1000,
'rootStiffness': 0.5,
'tipStiffness': 0,
'simulate': True,
'stiffness': 0.5,
'stiffnessStrength': 1,
'stiffnessDamping': 0,
'stiffnessCurve': (1, 1, 1, 1),
'stiffnessStrengthCurve': (1, 1, 1, 1),
'stiffnessDampingCurve': (1, 1, 1, 1),
'bendStiffnessCurve': (1, 1, 1, 1),
'interactionStiffnessCurve': (1, 1, 1, 1),
'wind': (0, 0, 0),
'windNoise': 0,
'visualizeBones': False,
'visualizeBoundingBox': False,
'visualizeCapsules': False,
'visualizeControlVertices': False,
'visualizeCullSphere': False,
'visualizeDiffuseBone': False,
'visualizeFrames': False,
'visualizeGrowthMesh': False,
'visualizeGuideHairs': False,
'visualizeHairInteractions': False,
'visualizeHairSkips': 0,
'visualizeLocalPos': False,
'visualizePinConstraints': False,
'visualizeShadingNormals': False,
'visualizeSkinnedGuideHairs': False,
'drawRenderHairs': True,
'enable': True
}