templateClothMat = {
'verticalStretchingStiffness': 1.0, 
'horizontalStretchingStiffness': 1.0, 
'bendingStiffness': 0.5, 
'shearingStiffness': 0.5, 
'tetherStiffness': 1, 
'tetherLimit': 1, 
'orthoBending': False, 
'verticalStiffnessScaling_compressionRange': 1.0, 
'verticalStiffnessScaling_stretchRange': 1.0, 
'verticalStiffnessScaling_scale': 0.5, 
'horizontalStiffnessScaling_compressionRange': 1.0, 
'horizontalStiffnessScaling_stretchRange': 1.0, 
'horizontalStiffnessScaling_scale': 0.5, 
'bendingStiffnessScaling_compressionRange': 1.0, 
'bendingStiffnessScaling_stretchRange': 1.0, 
'bendingStiffnessScaling_scale': 0.5, 
'shearingStiffnessScaling_compressionRange': 1.0, 
'shearingStiffnessScaling_stretchRange': 1.0, 
'shearingStiffnessScaling_scale': 0.5, 
'damping': 0.1, 
'stiffnessFrequency': 100.0, 
'drag': 0, 
'comDamping': False, 
'friction': 0.25, 
'massScale': 25.0, 
'solverIterations': 5, 
'solverFrequency': 250.0, 
'gravityScale': 1, 
'inertiaScale': 1, 
'hardStretchLimitation': 0.0, 
'maxDistanceBias': 0.0, 
'hierarchicalSolverIterations': 0, 
'selfcollisionThickness': 0.0, 
'selfcollisionSquashScale': 0.0, 
'selfcollisionStiffness': 0.0
}

templateClothSim = {
'hierarchicalLevels': 0, 
'thickness': 0.06, 
'virtualParticleDensity': 0.0, 
'gravityDirection': (0,0,-1), 
'sleepLinearVelocity': 0.0, 
'disableCCD': False, 
'untangling': False, 
'twowayInteraction': False, 
'restLengthScale': 1.0
}